### ISSUE TITLE
Multiclass oversampling for multi-minority problem

### ISSUE THREAD

**Issue by arilwan** [analyticalmindsltd/smote_variants#22]
Hi @gykovacs 

I am having at hand, a multiclass(5 classes) multi-minority(2 minority classes) problem, so I implored the approach you demonstrated in notebook `001_multiclass_oversampling`. However, it appears only 1-minority class was oversample. Here's what I get checking the class distributions before and after oversampling.

```
Oversampling with smote_varinats: Class distributions:
class distributions before smote_variants
class 0 - samples: 181126
class 1 - samples: 5694
class 2 - samples: 78727
class 3 - samples: 113578
class 4 - samples: 5971
Print Enter to continue:...

2020-05-04 19:20:24,822:INFO:distance_SMOTE: Running sampling via ('distance_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
class distributions atfer smote_variants
class 0 - samples: 181126
class 1 - samples: 181126
class 2 - samples: 78727
class 3 - samples: 113578
class 4 - samples: 5971
Print Enter to continue:...
```

I expect the other class `class 4` to be resampled as well. What am I missing?

**Comment by gykovacs** [comment]
Hi @arilwan ,

sorry for the late reply, I'm looking into this right now.

**Comment by gykovacs** [comment]
I just checked the code, it seems to work (the sample code on the front page of the repo). Could you please share your code, and some details of the data? (How are the y labels represented, are they integers, or objects?)

**Comment by arilwan** [comment]
@gykovacs I must have bugs in my code. I can confirm all works well, closing.

**Comment by shwetashrmgithub** [comment]
@gykovacs Great work! I want to compare some of the variants of SMOTE and I follow your Code **smote_variants/examples/003_evaluation_one_dataset.ipynb** and also looked some examples of your paper, but it has oversampled the entire dataset which should not be the case as it must be validated on testing data only.. Could you please provide me the code how I can compare Auc applying SMOTE, BorderlineSMOTE,  AHC, CLuster SMOTE, ADASYN..Thanks in advance
Mail id: shwetabhardwajj15@gmail.com

**Comment by arilwan** [comment]
@shwetashrmgithub  I suggest you open a new issue since this issue is resolved and closed already.
