### ISSUE TITLE
Implement 'verbose' parameter (feature request)

### ISSUE THREAD

**Issue by Jose-Verdu-Diaz** [analyticalmindsltd/smote_variants#72]
Hello, I would love to have control over the logging of the oversampling with a 'verbose' (bool) parameter. I find that the logging can end up cluttering the terminal too much, especially for multiclass oversampling.

I forked the repo and tried implementing it to the OverSamplingBase, just to realise that the logger is created at many other levels, so I'm unsure of what would be the cleanest solution

Thanks for this work!

**Comment by gykovacs** [comment]
Hi! Thank you for raising. In fact, you have control. You should query the package's logger as

```python
import logging
logger = logging.getLogger('smote_variants')
```

and then you can set the level of logging to what suits the most, for example:

```
logger.setLevel(logging.ERROR)
```

should suppress all logging. Let me know if it works!
```

**Comment by Jose-Verdu-Diaz** [comment]
That worked great, thank you!
